# Generated by Django 4.0.1 on 2022-01-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
